# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "atob-2.1.2" = {
      name = "atob";
      packageName = "atob";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.1.2.tgz";
        sha512 = "Wm6ukoaOGJi/73p/cl2GvLjTI5JM1k/O14isD73YML8StrH/7/lRFgmg8nICZgD3bZZvjwCGxtMOD3wWNAu8cg==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "breakdance-3.0.1" = {
      name = "breakdance";
      packageName = "breakdance";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/breakdance/-/breakdance-3.0.1.tgz";
        sha1 = "475a989c8389f522876890ba14f397adfb0e3184";
      };
    };
    "breakdance-util-0.1.5" = {
      name = "breakdance-util";
      packageName = "breakdance-util";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/breakdance-util/-/breakdance-util-0.1.5.tgz";
        sha1 = "c76bb92bac25f94d2adb90ead3b3e54140466b98";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "cheerio-0.22.0" = {
      name = "cheerio";
      packageName = "cheerio";
      version = "0.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cheerio/-/cheerio-0.22.0.tgz";
        sha1 = "a9baa860a3f9b595a6b81b1a86873121ed3a269e";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "component-emitter-1.3.0" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.3.0.tgz";
        sha512 = "Rd3se6QB+sO1TwqZjscQrurpEPIfO0/yYnSin6Q/rD3mOutHvUrCAhJub3r90uNb+SESBuE0QYoB90YdfatsRg==";
      };
    };
    "condense-newlines-0.2.1" = {
      name = "condense-newlines";
      packageName = "condense-newlines";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/condense-newlines/-/condense-newlines-0.2.1.tgz";
        sha1 = "3de985553139475d32502c83b02f60684d24c55f";
      };
    };
    "css-select-1.2.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-1.2.0.tgz";
        sha1 = "2b3a110539c5355f1cd8d314623e870b121ec858";
      };
    };
    "css-what-2.1.3" = {
      name = "css-what";
      packageName = "css-what";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-2.1.3.tgz";
        sha512 = "a+EPoD+uZiNfh+5fxw2nO9QwFa6nJe2Or35fGY6Ipw1R3R4AGz1d1TEZrCegvw2YTmZ0jXirGYlzxxpYSHwpEg==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "define-property-0.2.5" = {
      name = "define-property";
      packageName = "define-property";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-0.2.5.tgz";
        sha1 = "c35b1ef918ec3c990f9a5bc57be04aacec5c8116";
      };
    };
    "define-property-1.0.0" = {
      name = "define-property";
      packageName = "define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-1.0.0.tgz";
        sha1 = "769ebaaf3f4a63aad3af9e8d304c9bbe79bfb0e6";
      };
    };
    "detect-indent-5.0.0" = {
      name = "detect-indent";
      packageName = "detect-indent";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-indent/-/detect-indent-5.0.0.tgz";
        sha1 = "3871cc0a6a002e8c3e5b3cf7f336264675f06b9d";
      };
    };
    "diacritics-map-0.1.0" = {
      name = "diacritics-map";
      packageName = "diacritics-map";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diacritics-map/-/diacritics-map-0.1.0.tgz";
        sha1 = "6dfc0ff9d01000a2edf2865371cac316e94977af";
      };
    };
    "dom-serializer-0.1.1" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.1.tgz";
        sha512 = "l0IU0pPzLWSHBcieZbpOKgkIn3ts3vAh7ZuFyXNwJxJXk/c4Gwj9xaTJwIDVQCXawWD0qb3IzMGH5rglQaO0XA==";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domelementtype-2.0.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.0.1.tgz";
        sha512 = "5HOHUDsYZWV8FGWN0Njbr/Rn7f/eWSQi1v7+HsUVwXgn8nWWlL64zKDkS0n8ZmQ3mlWOMuXOnR+7Nx/5tMO5AQ==";
      };
    };
    "domhandler-2.4.2" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.4.2.tgz";
        sha512 = "JiK04h0Ht5u/80fdLMCEmV4zkNh2BcoMFBmZ/91WtYZ8qVXSKjiw7fXMgFPnHcSZgOo3XdinHvmnDUeMf5R4wA==";
      };
    };
    "domhandler-3.0.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-3.0.0.tgz";
        sha512 = "eKLdI5v9m67kbXQbJSNn1zjh0SDzvzWVWtX+qEI3eMjZw8daH9k8rlj1FZY9memPwjiskQFbe7vHVVJIAqoEhw==";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha1 = "dcd8488a26f563d61079e48c9f7b7e32373682cf";
      };
    };
    "domutils-2.0.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.0.0.tgz";
        sha512 = "n5SelJ1axbO636c2yUtOGia/IcJtVtlhQbFiVDBZHKV5ReJO1ViX7sFEemtuyoAnBxk5meNSYgA8V4s0271efg==";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "entities-2.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.0.0.tgz";
        sha512 = "D9f7V0JSRwIxlRI2mjMqufDrRDnx8p+eEOz7aUM9SuvF8gsBzra0/6tbjl1m8eQHrZlYj6PxqE00hZ1SAIKPLw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "export-files-2.1.1" = {
      name = "export-files";
      packageName = "export-files";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/export-files/-/export-files-2.1.1.tgz";
        sha1 = "bbf64574053a09e4eb98e5f43501d572b2c3ce7f";
      };
    };
    "extend-shallow-2.0.1" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-2.0.1.tgz";
        sha1 = "51af7d614ad9a9f610ea1bafbb989d6b1c56890f";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha1 = "81068d295a8142ec0ac726c6e2200c30fb6d5e80";
      };
    };
    "for-own-0.1.5" = {
      name = "for-own";
      packageName = "for-own";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-0.1.5.tgz";
        sha1 = "5265c681a4f294dabbf17c9509b6763aa84510ce";
      };
    };
    "get-value-2.0.6" = {
      name = "get-value";
      packageName = "get-value";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-value/-/get-value-2.0.6.tgz";
        sha1 = "dc15ca1c672387ca76bd37ac0a395ba2042a2c28";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "htmlparser2-3.10.1" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.10.1.tgz";
        sha512 = "IgieNijUMbkDovyoKObU1DUhm1iwNYE/fuifEoEHfd1oZKZDaONBSkal7Y01shxsM49R4XaMdGez3WnF9UfiCQ==";
      };
    };
    "htmlparser2-4.1.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-4.1.0.tgz";
        sha512 = "4zDq1a1zhE4gQso/c5LP1OtrhYTncXNSpvJYtWJBtXAETPlMfi3IFNjGuQbYLuVY4ZR0QMqRVvo4Pdy9KLyP8Q==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-accessor-descriptor-0.1.6" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-0.1.6.tgz";
        sha1 = "a9e12cb3ae8d876727eeef3843f8a0897b5c98d6";
      };
    };
    "is-accessor-descriptor-1.0.0" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-1.0.0.tgz";
        sha512 = "m5hnHTkcVsPfqx3AKlyttIPb7J+XykHvJP2B9bZDjlhLIoEq4XoK64Vg7boZlVWYK6LUY94dYPEE7Lh0ZkZKcQ==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-data-descriptor-0.1.4" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-0.1.4.tgz";
        sha1 = "0b5ee648388e2c860282e793f1856fec3f301b56";
      };
    };
    "is-data-descriptor-1.0.0" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-1.0.0.tgz";
        sha512 = "jbRXy1FmtAoCjQkVmIVYwuuqDFUbaOeDjmed1tOGPrsMhtJA4rD9tkgA0F1qJ3gRFRXcHYVkdeaP50Q5rE/jLQ==";
      };
    };
    "is-descriptor-0.1.6" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-0.1.6.tgz";
        sha512 = "avDYr0SB3DwO9zsMov0gKCESFYqCnE4hq/4z3TdUlukEy5t9C0YRq7HLrsN52NAcqXKaepeCD0n+B0arnVG3Hg==";
      };
    };
    "is-descriptor-1.0.2" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-1.0.2.tgz";
        sha512 = "2eis5WqQGV7peooDyLmNEPUrps9+SXX5c9pL3xEB+4e9HnGuDa7mB7kHxHw4CbqS9k1T2hOH3miL8n8WtiYVtg==";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha1 = "62b110e289a471418e3ec36a617d472e301dfc89";
      };
    };
    "is-extendable-1.0.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-1.0.1.tgz";
        sha512 = "arnXMxT1hhoKo9k1LZdmlNyJdDDfy2v0fXjFlmok4+i8ul/6WlbVge9bhM74OpNPQPMGUToDtz+KXa1PneJxOA==";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "h5PpgXkWitc38BBMYawTYMWJHFZJVnBquFE57xFpjB8pJFiF6gZ+bU+WyI/yqXiFR5mdLsgYNaPe8uao6Uv9Og==";
      };
    };
    "is-self-closing-1.0.1" = {
      name = "is-self-closing";
      packageName = "is-self-closing";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-self-closing/-/is-self-closing-1.0.1.tgz";
        sha512 = "E+60FomW7Blv5GXTlYee2KDrnG6srxF7Xt1SjrhWUGUEsTFIqY/nq2y3DaftCsgUMdh89V07IVfhY9KIJhLezg==";
      };
    };
    "is-whitespace-0.3.0" = {
      name = "is-whitespace";
      packageName = "is-whitespace";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-whitespace/-/is-whitespace-0.3.0.tgz";
        sha1 = "1639ecb1be036aec69a54cbb401cfbed7114ab7f";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha1 = "4e431e92b11a9731636aa1f9c8d1ccbcfdab78df";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "kind-of-5.1.0" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-5.1.0.tgz";
        sha512 = "NGEErnH6F2vUuXDh+OlbcKW7/wOcfdRHaZ7VWtqCztfHri/++YKmP51OdWeGPuqCOba6kk2OTe5d02VmTB80Pw==";
      };
    };
    "kind-of-6.0.3" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
        sha512 = "dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
      };
    };
    "lazy-cache-1.0.4" = {
      name = "lazy-cache";
      packageName = "lazy-cache";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy-cache/-/lazy-cache-1.0.4.tgz";
        sha1 = "a1d78fc3a50474cb80845d3b3b6e1da49a446e8e";
      };
    };
    "lazy-cache-2.0.2" = {
      name = "lazy-cache";
      packageName = "lazy-cache";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy-cache/-/lazy-cache-2.0.2.tgz";
        sha1 = "b9190a4f913354694840859f8a8f7084d8822264";
      };
    };
    "lodash.assignin-4.2.0" = {
      name = "lodash.assignin";
      packageName = "lodash.assignin";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assignin/-/lodash.assignin-4.2.0.tgz";
        sha1 = "ba8df5fb841eb0a3e8044232b0e263a8dc6a28a2";
      };
    };
    "lodash.bind-4.2.1" = {
      name = "lodash.bind";
      packageName = "lodash.bind";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.bind/-/lodash.bind-4.2.1.tgz";
        sha1 = "7ae3017e939622ac31b7d7d7dcb1b34db1690d35";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lodash.defaults-4.2.0" = {
      name = "lodash.defaults";
      packageName = "lodash.defaults";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.defaults/-/lodash.defaults-4.2.0.tgz";
        sha1 = "d09178716ffea4dde9e5fb7b37f6f0802274580c";
      };
    };
    "lodash.escaperegexp-4.1.2" = {
      name = "lodash.escaperegexp";
      packageName = "lodash.escaperegexp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.escaperegexp/-/lodash.escaperegexp-4.1.2.tgz";
        sha1 = "64762c48618082518ac3df4ccf5d5886dae20347";
      };
    };
    "lodash.filter-4.6.0" = {
      name = "lodash.filter";
      packageName = "lodash.filter";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.filter/-/lodash.filter-4.6.0.tgz";
        sha1 = "668b1d4981603ae1cc5a6fa760143e480b4c4ace";
      };
    };
    "lodash.flatten-4.4.0" = {
      name = "lodash.flatten";
      packageName = "lodash.flatten";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.flatten/-/lodash.flatten-4.4.0.tgz";
        sha1 = "f31c22225a9632d2bbf8e4addbef240aa765a61f";
      };
    };
    "lodash.foreach-4.5.0" = {
      name = "lodash.foreach";
      packageName = "lodash.foreach";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.foreach/-/lodash.foreach-4.5.0.tgz";
        sha1 = "1a6a35eace401280c7f06dddec35165ab27e3e53";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.map-4.6.0" = {
      name = "lodash.map";
      packageName = "lodash.map";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.map/-/lodash.map-4.6.0.tgz";
        sha1 = "771ec7839e3473d9c4cde28b19394c3562f4f6d3";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lodash.mergewith-4.6.2" = {
      name = "lodash.mergewith";
      packageName = "lodash.mergewith";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.mergewith/-/lodash.mergewith-4.6.2.tgz";
        sha512 = "GK3g5RPZWTRSeLSpgP8Xhra+pnjBC56q9FZYe1d5RN3TJ35dbkGy3YqBSMbyCrlbi+CM9Z3Jk5yTL7RCsqboyQ==";
      };
    };
    "lodash.pick-4.4.0" = {
      name = "lodash.pick";
      packageName = "lodash.pick";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.pick/-/lodash.pick-4.4.0.tgz";
        sha1 = "52f05610fff9ded422611441ed1fc123a03001b3";
      };
    };
    "lodash.reduce-4.6.0" = {
      name = "lodash.reduce";
      packageName = "lodash.reduce";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.reduce/-/lodash.reduce-4.6.0.tgz";
        sha1 = "f1ab6b839299ad48f784abbf476596f03b914d3b";
      };
    };
    "lodash.reject-4.6.0" = {
      name = "lodash.reject";
      packageName = "lodash.reject";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.reject/-/lodash.reject-4.6.0.tgz";
        sha1 = "80d6492dc1470864bbf583533b651f42a9f52415";
      };
    };
    "lodash.some-4.6.0" = {
      name = "lodash.some";
      packageName = "lodash.some";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.some/-/lodash.some-4.6.0.tgz";
        sha1 = "1bb9f314ef6b8baded13b549169b2a945eb68e4d";
      };
    };
    "map-cache-0.2.2" = {
      name = "map-cache";
      packageName = "map-cache";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-cache/-/map-cache-0.2.2.tgz";
        sha1 = "c32abd0bd6525d9b051645bb4f26ac5dc98a0dbf";
      };
    };
    "mixin-deep-1.3.2" = {
      name = "mixin-deep";
      packageName = "mixin-deep";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mixin-deep/-/mixin-deep-1.3.2.tgz";
        sha512 = "WRoDn//mXBiJ1H40rqa3vH0toePwSsGb45iInWlTySa+Uu4k3tYUSxa2v1KqAiLtvlrSzaExqS1gtk96A9zvEA==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "nth-check-1.0.2" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-1.0.2.tgz";
        sha512 = "WeBOdju8SnzPN5vTUJYxYUxLeXpCaVP5i5e0LF8fg7WORF2Wd7wFX/pk0tYZk7s8T+J7VLy0Da6J1+wCT0AtHg==";
      };
    };
    "object.omit-2.0.1" = {
      name = "object.omit";
      packageName = "object.omit";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.omit/-/object.omit-2.0.1.tgz";
        sha1 = "1a9c744829f39dbb858c76ca3579ae2a54ebd1fa";
      };
    };
    "object.pick-1.3.0" = {
      name = "object.pick";
      packageName = "object.pick";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.pick/-/object.pick-1.3.0.tgz";
        sha1 = "87a10ac4c1694bd2e1cbf53591a66141fb5dd747";
      };
    };
    "pixl-args-1.0.3" = {
      name = "pixl-args";
      packageName = "pixl-args";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-args/-/pixl-args-1.0.3.tgz";
        sha1 = "63c0a67a921fbb1b285ccca5192a49910feda334";
      };
    };
    "pixl-class-1.0.3" = {
      name = "pixl-class";
      packageName = "pixl-class";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-class/-/pixl-class-1.0.3.tgz";
        sha512 = "YS3MS4IuBNvy1gAuMJtQiZPMdmRjK2EwqomJNUG3PJtCz5bbG5MWgY7xV780jx/2oIj/IHNYGyZmfqQRs0KTZw==";
      };
    };
    "postcss-7.0.27" = {
      name = "postcss";
      packageName = "postcss";
      version = "7.0.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-7.0.27.tgz";
        sha512 = "WuQETPMcW9Uf1/22HWUWP9lgsIC+KEHg2kozMflKjbeUtw9ujvFX6QmIfozaErDkmLWS9WEnEdEe6Uo9/BNTdQ==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "resolve-url-0.2.1" = {
      name = "resolve-url";
      packageName = "resolve-url";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-url/-/resolve-url-0.2.1.tgz";
        sha1 = "2c637fe77c893afd2a663fe21aa9080068e2052a";
      };
    };
    "safe-buffer-5.2.0" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.0.tgz";
        sha512 = "fZEwUGbVl7kouZs1jCdMLdt95hdIv0ZeHg6L7qPeciMZhZ+/gdesW4wgTARkrFWEpspjEATAzUGPG8N2jJiwbg==";
      };
    };
    "sanitize-html-1.22.1" = {
      name = "sanitize-html";
      packageName = "sanitize-html";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitize-html/-/sanitize-html-1.22.1.tgz";
        sha512 = "++IMC00KfMQc45UWZJlhWOlS9eMrME38sFG9GXfR+k6oBo9JXSYQgTOZCl9j3v/smFTRNT9XNwz5DseFdMY+2Q==";
      };
    };
    "self-closing-tags-1.0.1" = {
      name = "self-closing-tags";
      packageName = "self-closing-tags";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/self-closing-tags/-/self-closing-tags-1.0.1.tgz";
        sha512 = "7t6hNbYMxM+VHXTgJmxwgZgLGktuXtVVD5AivWzNTdJBM4DBjnDKDzkf2SrNjihaArpeJYNjxkELBu1evI4lQA==";
      };
    };
    "set-getter-0.1.0" = {
      name = "set-getter";
      packageName = "set-getter";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-getter/-/set-getter-0.1.0.tgz";
        sha1 = "d769c182c9d5a51f409145f2fba82e5e86e80376";
      };
    };
    "snapdragon-0.11.5" = {
      name = "snapdragon";
      packageName = "snapdragon";
      version = "0.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon/-/snapdragon-0.11.5.tgz";
        sha512 = "iC2oF+H+TjiZN4a7I5HNUH8imAFT9z3GydV8X5ZFLcBiDYROWNeqI34BHArXTVO/RGs88STtAtiMP3tCiNdUYg==";
      };
    };
    "snapdragon-cheerio-1.1.0" = {
      name = "snapdragon-cheerio";
      packageName = "snapdragon-cheerio";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-cheerio/-/snapdragon-cheerio-1.1.0.tgz";
        sha1 = "16f3bd3fa1615f85c5f826504c5bb406cd340eb7";
      };
    };
    "snapdragon-node-1.0.6" = {
      name = "snapdragon-node";
      packageName = "snapdragon-node";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-node/-/snapdragon-node-1.0.6.tgz";
        sha1 = "2448d5ef6fea7f5e8fd5326a0a114854da271356";
      };
    };
    "snapdragon-util-1.0.6" = {
      name = "snapdragon-util";
      packageName = "snapdragon-util";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-util/-/snapdragon-util-1.0.6.tgz";
        sha1 = "8b3d2d6dec8930c90e054ba052e562ca1b3a621e";
      };
    };
    "snapdragon-util-2.1.1" = {
      name = "snapdragon-util";
      packageName = "snapdragon-util";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-util/-/snapdragon-util-2.1.1.tgz";
        sha1 = "552779df8a1493a0e78c06cc80953a262770957a";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-resolve-0.5.3" = {
      name = "source-map-resolve";
      packageName = "source-map-resolve";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-resolve/-/source-map-resolve-0.5.3.tgz";
        sha512 = "Htz+RnsXWk5+P2slx5Jh3Q66vhQj1Cllm0zvnaY98+NFx+Dv2CF/f5O/t8x+KaNdrdIAsruNzoh/KpialbqAnw==";
      };
    };
    "source-map-url-0.4.0" = {
      name = "source-map-url";
      packageName = "source-map-url";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-url/-/source-map-url-0.4.0.tgz";
        sha1 = "3e935d7ddd73631b97659956d55128e87b5084a3";
      };
    };
    "srcset-2.0.1" = {
      name = "srcset";
      packageName = "srcset";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/srcset/-/srcset-2.0.1.tgz";
        sha512 = "00kZI87TdRKwt+P8jj8UZxbfp7mK2ufxcIMWvhAOZNJTRROimpHeruWrGvCZneiuVDLqdyHefVp748ECTnyUBQ==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-attributes-0.2.0" = {
      name = "strip-attributes";
      packageName = "strip-attributes";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-attributes/-/strip-attributes-0.2.0.tgz";
        sha1 = "30ba227c6abf6356a51b2b68626c795f19280945";
      };
    };
    "strip-color-0.1.0" = {
      name = "strip-color";
      packageName = "strip-color";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-color/-/strip-color-0.1.0.tgz";
        sha1 = "106f65d3d3e6a2d9401cac0eb0ce8b8a702b4f7b";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-6.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-6.1.0.tgz";
        sha512 = "qe1jfm1Mg7Nq/NSh6XE24gPXROEVsWHxC1LIx//XNlD9iw7YZQGjZNjYN7xGaEG6iKdA8EtNFW6R0gjnVXp+wQ==";
      };
    };
    "to-object-path-0.3.0" = {
      name = "to-object-path";
      packageName = "to-object-path";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-object-path/-/to-object-path-0.3.0.tgz";
        sha1 = "297588b7b0e7e0ac08e04e672f85c1f4999e17af";
      };
    };
    "trim-leading-lines-0.1.1" = {
      name = "trim-leading-lines";
      packageName = "trim-leading-lines";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-leading-lines/-/trim-leading-lines-0.1.1.tgz";
        sha1 = "0e7cac3e83042dcf95a74ed36966f17744d5c169";
      };
    };
    "trim-trailing-lines-1.1.3" = {
      name = "trim-trailing-lines";
      packageName = "trim-trailing-lines";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim-trailing-lines/-/trim-trailing-lines-1.1.3.tgz";
        sha512 = "4ku0mmjXifQcTVfYDfR5lpgV7zVqPg6zV9rdZmwOPqq0+Zq19xDqEgagqVbc4pOOShbncuAOIs59R3+3gcF3ZA==";
      };
    };
    "typeof-article-0.1.1" = {
      name = "typeof-article";
      packageName = "typeof-article";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typeof-article/-/typeof-article-0.1.1.tgz";
        sha1 = "9f07e733c3fbb646ffa9e61c08debacd460e06af";
      };
    };
    "unescape-0.2.0" = {
      name = "unescape";
      packageName = "unescape";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unescape/-/unescape-0.2.0.tgz";
        sha1 = "b78b9b60c86f1629df181bf53eee3bc8d6367ddf";
      };
    };
    "urix-0.1.0" = {
      name = "urix";
      packageName = "urix";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/urix/-/urix-0.1.0.tgz";
        sha1 = "da937f7a62e21fec1fd18d49b35c2935067a6c72";
      };
    };
    "use-3.1.1" = {
      name = "use";
      packageName = "use";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/use/-/use-3.1.1.tgz";
        sha512 = "cwESVXlO3url9YWlFW/TA9cshCEhtu7IKJ/p5soJ/gGpj7vbvFrAY/eIioQ6Dw23KjZhYgiIo8HOs1nQ2vr/oQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "word-regex-0.1.2" = {
      name = "word-regex";
      packageName = "word-regex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-regex/-/word-regex-0.1.2.tgz";
        sha1 = "a3bc7f2d222ce4a93c246c3ef69458f61f511639";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
in
{
  clipdown = nodeEnv.buildNodePackage {
    name = "clipdown";
    packageName = "clipdown";
    version = "1.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/clipdown/-/clipdown-1.0.1.tgz";
      sha512 = "yBEIG29r4ODTowWr3P4Z2CfL2wFP3ZldegwwtRYj2/w2Eip1KqbUTb8TJpvYZQhLkMb2TJyCi8xDZs7EwZx0/g==";
    };
    dependencies = [
      sources."ansi-styles-3.2.1"
      sources."atob-2.1.2"
      sources."boolbase-1.0.0"
      sources."breakdance-3.0.1"
      (sources."breakdance-util-0.1.5" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."snapdragon-util-1.0.6"
        ];
      })
      sources."chalk-2.4.2"
      sources."cheerio-0.22.0"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."component-emitter-1.3.0"
      sources."condense-newlines-0.2.1"
      sources."css-select-1.2.0"
      sources."css-what-2.1.3"
      sources."debug-2.6.9"
      sources."decode-uri-component-0.2.0"
      (sources."define-property-1.0.0" // {
        dependencies = [
          sources."is-accessor-descriptor-1.0.0"
          sources."is-data-descriptor-1.0.0"
          sources."is-descriptor-1.0.2"
          sources."kind-of-6.0.3"
        ];
      })
      sources."detect-indent-5.0.0"
      sources."diacritics-map-0.1.0"
      sources."dom-serializer-0.1.1"
      sources."domelementtype-1.3.1"
      sources."domhandler-2.4.2"
      sources."domutils-1.5.1"
      sources."entities-1.1.2"
      sources."escape-string-regexp-1.0.5"
      (sources."export-files-2.1.1" // {
        dependencies = [
          sources."lazy-cache-1.0.4"
        ];
      })
      sources."extend-shallow-2.0.1"
      sources."for-in-1.0.2"
      sources."for-own-0.1.5"
      sources."get-value-2.0.6"
      sources."has-flag-3.0.0"
      sources."htmlparser2-3.10.1"
      sources."inherits-2.0.4"
      sources."is-accessor-descriptor-0.1.6"
      sources."is-buffer-1.1.6"
      sources."is-data-descriptor-0.1.4"
      (sources."is-descriptor-0.1.6" // {
        dependencies = [
          sources."kind-of-5.1.0"
        ];
      })
      sources."is-extendable-0.1.1"
      sources."is-plain-object-2.0.4"
      sources."is-self-closing-1.0.1"
      sources."is-whitespace-0.3.0"
      sources."isobject-3.0.1"
      sources."kind-of-3.2.2"
      sources."lazy-cache-2.0.2"
      sources."lodash.assignin-4.2.0"
      sources."lodash.bind-4.2.1"
      sources."lodash.clonedeep-4.5.0"
      sources."lodash.defaults-4.2.0"
      sources."lodash.escaperegexp-4.1.2"
      sources."lodash.filter-4.6.0"
      sources."lodash.flatten-4.4.0"
      sources."lodash.foreach-4.5.0"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.map-4.6.0"
      sources."lodash.merge-4.6.2"
      sources."lodash.mergewith-4.6.2"
      sources."lodash.pick-4.4.0"
      sources."lodash.reduce-4.6.0"
      sources."lodash.reject-4.6.0"
      sources."lodash.some-4.6.0"
      sources."map-cache-0.2.2"
      (sources."mixin-deep-1.3.2" // {
        dependencies = [
          sources."is-extendable-1.0.1"
        ];
      })
      sources."ms-2.0.0"
      sources."nth-check-1.0.2"
      sources."object.omit-2.0.1"
      sources."object.pick-1.3.0"
      sources."pixl-args-1.0.3"
      sources."pixl-class-1.0.3"
      (sources."postcss-7.0.27" // {
        dependencies = [
          sources."source-map-0.6.1"
          sources."supports-color-6.1.0"
        ];
      })
      sources."readable-stream-3.6.0"
      sources."repeat-string-1.6.1"
      sources."resolve-url-0.2.1"
      sources."safe-buffer-5.2.0"
      (sources."sanitize-html-1.22.1" // {
        dependencies = [
          sources."dom-serializer-0.2.2"
          sources."domelementtype-2.0.1"
          sources."domhandler-3.0.0"
          sources."domutils-2.0.0"
          sources."entities-2.0.0"
          sources."htmlparser2-4.1.0"
        ];
      })
      sources."self-closing-tags-1.0.1"
      sources."set-getter-0.1.0"
      (sources."snapdragon-0.11.5" // {
        dependencies = [
          sources."define-property-0.2.5"
        ];
      })
      (sources."snapdragon-cheerio-1.1.0" // {
        dependencies = [
          sources."define-property-0.2.5"
        ];
      })
      (sources."snapdragon-node-1.0.6" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."snapdragon-util-1.0.6"
        ];
      })
      sources."snapdragon-util-2.1.1"
      sources."source-map-0.5.7"
      sources."source-map-resolve-0.5.3"
      sources."source-map-url-0.4.0"
      sources."srcset-2.0.1"
      sources."string_decoder-1.3.0"
      sources."strip-attributes-0.2.0"
      sources."strip-color-0.1.0"
      sources."supports-color-5.5.0"
      sources."to-object-path-0.3.0"
      sources."trim-leading-lines-0.1.1"
      sources."trim-trailing-lines-1.1.3"
      sources."typeof-article-0.1.1"
      sources."unescape-0.2.0"
      sources."urix-0.1.0"
      sources."use-3.1.1"
      sources."util-deprecate-1.0.2"
      sources."word-regex-0.1.2"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Convert rich HTML to Markdown in your clipboard (macOS only).";
      homepage = "https://github.com/jhuckaby/clipdown#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}